### ISSUE TITLE
Page: Image Alignment - Image missing (Codex)

### ISSUE THREAD

**Issue by bph** [abstractwp/theme-test-data#13]
### Screenshots, screen recordings

![Screen Shot 2022-09-23 at 18 27 14](https://user-images.githubusercontent.com/39980/192064883-cb7eb0bc-f27a-4659-96e7-b3d8be5b9875.png)

### URL

/page-image-alignment/

### Browser

Chrome Version 105.0.5195.125 (Official Build) (arm64)
Images link to: http://wptest.io/demo/wp-content/uploads/sites/2/2013/03/image-alignment-580x300-2.jpg

It's probably a quirk in the Codex Test unit. 

### Screen Size

Desktop

### Additional Info

Nothing else really.

**Comment by danhthong** [comment]
@bph Please get new release for this issue fixed.
